spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_demo
    username: root
    password: yangyi126
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
    password: yangyi126

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.yangyi.project.domain
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  config: classpath:log4j2.xml
  level:
    { com.bosideng.wecom.api: debug,
      com.bosideng.advert.api.feignUtils: debug }

ignore:
  paths:
    - '/error'
    - '/favicon.ico'
