spring:
  application:
    name: @project.artifactId@
  main:
    banner-mode: off
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: org.yangyi.project.entity
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:log4j2.xml
  level:
    { com.bosideng.wecom.api: debug, com.bosideng.advert.api.feignUtils: debug }
