spring:
  application:
    name: @project.artifactId@
  main:
    banner-mode: off
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.yangyi.project.**.po
  config-location: classpath:mybatis-config.xml

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

logging:
  config: classpath:log4j2.xml
#  level:
#    { org.yangyi.project.system.dao: debug, com.bosideng.advert.api.feignUtils: debug }

