spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bms
    username: root
    password: yangyi126
  redis:
    host: 127.0.0.1
    port: 6379
    password: yangyi126
    database: 0
    connect-timeout: 10000
    timeout: 10000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

server:
  port: 8080
